spring:
  application:
    name: ch4
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,info

cloud:
  aws:
    s3:
      bucket: ch4-yejin-profile-files